[package]
name = "simple_rust_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
